---
abstract: 'C implementation of GIS::Distance formulas.'
author:
  - 'Aran Clary Deltac <bluefeet@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GIS-Distance-Fast
no_index:
  directory:
    - inc
    - t
requires:
  GIS::Distance: 0.07
  perl: 5.8.3
resources:
  homepage: http://github.com/bluefeet/gis-distance-fast/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bluefeet/gis-distance-fast.git
version: 0.06
